apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-vip
  template:
    metadata:
      labels:
        app: kube-vip
    spec:
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.9.1
          args:
            - manager
          env:
          - name: vip_arp
            value: "true"
          - name: vip_nodename
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: vip_interface
            value: ens18
          - name: vip_cidr
            value: "32"
          - name: dns_mode
            value: first
          - name: svc_enable
            value: "true"
          - name: svc_leasename
            value: plndr-svcs-lock
          - name: vip_leaderelection
            value: "true"
          - name: vip_leasename
            value: plndr-cp-lock
          - name: vip_leaseduration
            value: "60"
          - name: vip_renewdeadline
            value: "45"
          - name: vip_retryperiod
            value: "15"
          - name: lb_enable
            value: "true"
          imagePullPolicy: IfNotPresent
          resources: {}
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      # Nur auf Worker Nodes laufen:
      nodeSelector:
         node-role.kubernetes.io/worker: ""
      tolerations:
        - operator: Exists
