apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-appdata
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-appdata-audiobookshelf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-media
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  volumeName: pv-nfs-media-audiobookshelf